CREATE DATABASE IF NOT EXISTS emissari_cs411;

USE emissari_cs411;

CREATE TABLE IF NOT EXISTS User (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    `Password` CHAR(255) NOT NULL,
    City VARCHAR(100) NULL,
    State VARCHAR(100) NULL,
    Country VARCHAR(100) NULL,
    Phone VARCHAR(100) NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Travel (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    User_ID BIGINT NOT NULL,
    Origin_City VARCHAR(100) NULL,
    Origin_Country VARCHAR(100) NULL,
    Destination_City VARCHAR(100) NULL,
    Destination_Country VARCHAR(100) NULL,
    Travel_Date DATE NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (User_ID) REFERENCES User (ID)
) ENGINE=InnoDB;

/* Originally Travel was named Travel_Plan. Drop this old table if exists. */
DROP TABLE IF EXISTS Travel_Plan;

CREATE TABLE IF NOT EXISTS Friend (
	User_ID1 BIGINT NOT NULL,
    User_ID2 BIGINT NOT NULL,
    Pending BIT NOT NULL DEFAULT 1,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (User_ID1, User_ID2),
    FOREIGN KEY (User_ID1) REFERENCES User (ID),
    FOREIGN KEY (User_ID2) REFERENCES User (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Wish (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    User_ID BIGINT NOT NULL,
    Description VARCHAR(1000) NOT NULL,
    Image BLOB NULL,
    Weight VARCHAR(50) NULL,
    Destination_City VARCHAR(100) NULL,
    Destination_Country VARCHAR(100) NULL,
    Max_Date DATE NULL,
    Compensation VARCHAR(100) NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (User_ID) REFERENCES User (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Message (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    Sender_ID BIGINT NOT NULL,
    Recipient_ID BIGINT NOT NULL,
    Title VARCHAR(255) NULL,
    Content VARCHAR(10000) NOT NULL,
    Unread BIT NOT NULL DEFAULT 1,
    Wish_ID BIGINT NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (Sender_ID) REFERENCES User (ID),
    FOREIGN KEY (Recipient_ID) REFERENCES User (ID),
    FOREIGN KEY (Wish_ID) REFERENCES Wish (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Help` (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    Wish_ID BIGINT NOT NULL,
    User_ID BIGINT NOT NULL,
    Requested BIT NOT NULL DEFAULT 0,
    Offered BIT NOT NULL DEFAULT 0,
    Created_By BIGINT NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (Wish_ID) REFERENCES Wish (ID),
    FOREIGN KEY (User_ID) REFERENCES User (ID),
    FOREIGN KEY (Created_By) REFERENCES User (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Review (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    User_ID BIGINT NOT NULL,
    Help_ID BIGINT NOT NULL,
    Recommended BIT NOT NULL,
    Comments VARCHAR(1000) NULL,
    Created_By BIGINT NULL,
    Created_On DATETIME NULL,
    Modified_On DATETIME NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (User_ID) REFERENCES User (ID),
    FOREIGN KEY (Help_ID) REFERENCES `Help` (ID),
    FOREIGN KEY (Created_By) REFERENCES User (ID)
) ENGINE=InnoDB;